### ISSUE TITLE
Detect garbage files quickly 

### ISSUE THREAD

**Issue by jayunit100** [koki/short#203]
Running short against an html file gives:  

```
Use flag '--verbose-errors' for more detailed error info.
Error: parsing stdin: error converting YAML to JSON: yaml: line 318: mapping values are not allowed in this context
```

Would be bbetter to detect that its not even close to valid yml , probbably ...

**Comment by wlan0** [comment]
We do YAML validation while parsing by utilizing the Kubernetes YAML parser/validator - https://github.com/koki/short/blob/master/parser/parser.go#L46

The output you pasted above is from Kuberenetes' YAML parser. It parses YAML and validates it by converting it to JSON and then to a `map[string]interface{}`.

This is done so that both YAML and JSON are supported. More info here - https://github.com/ghodss/yaml

**Comment by wlan0** [comment]
Closing this. Re-open if there is a different issue here.
